### PR TITLE
JS reverse routing instead of meta tag

### PR DESCRIPTION
**Pull request by naderghanbari**
Use JavaScript reverse routing instead of assembling the WebSockets URL by appending the `email` to the partially assembled url in html meta tag.

### CODE REVIEW

**Comment by naderghanbari** [comment]
This has a tiny advantage over assembling manually:
* If for any reason in future the route changes, there is no guarantee that `:email` path variable will be still at the end of the URL, so simply appending it to the URL might fail.
* No need to keep the meta tag in html file (true that state is saved in local storage anyway but being less stateful is being more stateless :)

The only disadvantage is polluting the global js namespace, but anyway this is the recommended (standard?) way of doing it in Play.

**Comment by naderghanbari** [comment]
Updated the pull request by removing the `index.html` from it.

**Comment by ktoso** [comment]
LGTM, but maybe someone of the play team could confirm as well // @dotta @wsargent @jroper

**Comment by jroper** [comment]
LGTM

**Comment by ktoso** [comment]
Thanks James :)

**Pull request merged**
